project:
  type: website

website:
  title: "Ancient Woodland Exploration"
  navbar:
    left:
      - text: "AW Extent Explorer"
        file: AW extent exploration.qmd

format:
  html:
    theme: cosmo
    toc: true